// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


namespace VidyoClient
{
	/// <summary>
	/// This type indicates the result of an attempt to log in to some service.
	/// </summary>
	public enum CalendarCreateCode {
		/// <summary>The calendar instance was created successfully.</summary>
		CalendarcreatecodeOk,
		/// <summary>Service name not found in the list of registered services. Must be added first using VidyoCalendarManagerRegisterCalendarService</summary>
		CalendarcreatecodeSvcNotRegistered,
		/// <summary>Problems occured trying to load the calendar plugin library module.</summary>
		CalendarcreatecodeLibraryLoadFailed,
		/// <summary>Problems occured trying to load the calendar plugin library module.</summary>
		CalendarcreatecodeInvalidLibraryVersion,
		/// <summary>Found an existing instance with the same calendar service ID (plugin library) and calendar name (folder).</summary>
		CalendarcreatecodeExistingInstance,
		/// <summary>Failure occured constructing the calendar plugin object.</summary>
		CalendarcreatecodeCalendarPluginConstructFailure,
		/// <summary>The credentials required .</summary>
		CalendarcreatecodeCalendarPluginInvalidCredentials,
		/// <summary>The calendar Id provided was not known to the plugin service.</summary>
		CalendarcreatecodeCalendarPluginInvalidCalendarId,
		/// <summary>Failure occured constructing the VidyoCalendar object.</summary>
		CalendarcreatecodeVidyoCalendarConstructFailure,
		/// <summary>VidyoCalendar instance was successfully destroyed.</summary>
		CalendarcreatecodeVidyoCalendarDestroyed,
		/// <summary>The login failed for some other miscellaneous error.</summary>
		CalendarcreatecodeGeneralError
	}
}
