// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


namespace VidyoClient
{
	/// <summary>
	/// This enum contains type values that releate directly to HTML form input fields.
	/// </summary>
	public enum FormFieldType {
		/// <summary>HTML form field type for a text input.</summary>
		FormfieldtypeText,
		/// <summary>HTML form field type for a textarea input.</summary>
		FormfieldtypeTextArea,
		/// <summary>HTML form field type for a password input.</summary>
		FormfieldtypePassword,
		/// <summary>HTML form field type for a checkbox input.</summary>
		FormfieldtypeCheckbox,
		/// <summary>HTML form field type for a radio input.</summary>
		FormfieldtypeRadio,
		/// <summary>HTML form field type for a dropdown select input.</summary>
		FormfieldtypeSelect
	}
}
