// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


namespace VidyoClient
{
	/// <summary>
	/// This enum is used to represent the wrapping modes defined for a textarea HTML form input field.
	/// </summary>
	public enum FormFieldTextWrapMode {
		/// <summary>No wrapping</summary>
		FormfieldtextwrapmodeOff,
		/// <summary>Shows linebreaks, but sends text as entered</summary>
		FormfieldtextwrapmodeVirtual,
		/// <summary>Inserts linebreaks as needed and sends text with them.</summary>
		FormfieldtextwrapmodePhysical
	}
}
