// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


namespace VidyoClient
{
	/// <summary>
	/// Represents the media format.
	/// </summary>
	public enum MediaFormat {
		/// <summary></summary>
		MediaformatIN16,
		/// <summary></summary>
		MediaformatFL32,
		/// <summary></summary>
		MediaformatNULL,
		/// <summary></summary>
		MediaformatI420,
		/// <summary></summary>
		MediaformatYU12,
		/// <summary></summary>
		MediaformatYUYV,
		/// <summary></summary>
		MediaformatYUY2,
		/// <summary></summary>
		Mediaformatyuvs,
		/// <summary></summary>
		Mediaformat2vuy,
		/// <summary></summary>
		MediaformatUYVY,
		/// <summary></summary>
		MediaformatHDYC,
		/// <summary></summary>
		Mediaformatyuv2,
		/// <summary></summary>
		Mediaformatyuvu,
		/// <summary></summary>
		MediaformatNV12,
		/// <summary></summary>
		MediaformatNV21,
		/// <summary></summary>
		Mediaformat24BG,
		/// <summary></summary>
		Mediaformatraw,
		/// <summary></summary>
		MediaformatBGRA,
		/// <summary></summary>
		MediaformatRGBA,
		/// <summary></summary>
		MediaformatARGB,
		/// <summary></summary>
		MediaformatBYR1,
		/// <summary></summary>
		MediaformatBYR2,
		/// <summary></summary>
		MediaformatJPEG,
		/// <summary></summary>
		MediaformatMJPG,
		/// <summary></summary>
		Mediaformatdmb1,
		/// <summary></summary>
		Mediaformatavc1,
		/// <summary></summary>
		Mediaformathvc1,
		/// <summary></summary>
		MediaformatM420,
		/// <summary></summary>
		Mediaformat420f,
		/// <summary></summary>
		Mediaformat420v,
		/// <summary></summary>
		MediaformatY8
	}
}
