// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


namespace VidyoClient
{
	/// <summary>
	/// This type indicates the result of a search for a meeting(s).
	/// </summary>
	public enum MeetingAttendeesSearchResult {
		/// <summary>The search operation was successful.</summary>
		MeetingattendeessearchresultOk,
		/// <summary>Starting index is beyond number of result records.</summary>
		MeetingattendeessearchresultIndexOutOfRange,
		/// <summary>No records found for the search.</summary>
		MeetingattendeessearchresultNoRecords,
		/// <summary>The search result failed due to request timeout.</summary>
		MeetingattendeessearchresultNoResponse,
		/// <summary>The search result failed due to some miscellaneous local problem.</summary>
		MeetingattendeessearchresultMiscLocalError,
		/// <summary>The search result failed due to some miscellaneous remote problem.</summary>
		MeetingattendeessearchresultMiscRemoteError
	}
}
