// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


namespace VidyoClient
{
	/// <summary>
	/// This type indicates the result of a search for a meeting(s).
	/// </summary>
	public enum MeetingSearchResult {
		/// <summary>The search operation was successful.</summary>
		MeetingsearchresultOk,
		/// <summary>Request to perform search contains proper values and is being processed.</summary>
		MeetingsearchresultProcessing,
		/// <summary>No records found for the search.</summary>
		MeetingsearchresultNoRecords,
		/// <summary>Index for search does not fall within total number of records of existing search set, based on page size.</summary>
		MeetingsearchresultInvalidIndex,
		/// <summary>Date range has either, invalid begin or end date values, or end date is before begin date .</summary>
		MeetingsearchresultInvalidDateTimeRange,
		/// <summary>The search result failed due to request timeout.</summary>
		MeetingsearchresultNoResponse,
		/// <summary>Could not execute the search due to the calendar not being in a connected state.</summary>
		MeetingsearchresultNotConnected,
		/// <summary>Error returned by the plugin trying to initiate the search.</summary>
		MeetingsearchresultPluginError,
		/// <summary>The search result failed due to some miscellaneous local problem.</summary>
		MeetingsearchresultMiscLocalError,
		/// <summary>The search result failed due to some miscellaneous remote problem.</summary>
		MeetingsearchresultMiscRemoteError
	}
}
