// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


namespace VidyoClient
{
	/// <summary>
	/// This type indicates the result of an attempt to create a meeting.
	/// </summary>
	public enum MeetingActionResult {
		/// <summary>The meeting was created successfully.</summary>
		MeetingactionresultOk,
		/// <summary>Could not find an existing record to create the meeting object from.</summary>
		MeetingactionresultNoRecord,
		/// <summary>The calendar resource did not respond in a reasonable amount of time for the intended action.</summary>
		MeetingactionresultNoResponse,
		/// <summary>The user is not allowed to create a meeting.</summary>
		MeetingactionresultUnauthorized,
		/// <summary>The server is rejecting the request to perform an action on the meeting due to some miscellaneous problem with the request.</summary>
		MeetingactionresultMiscLocalError,
		/// <summary>The server is rejecting the request to perform an action on the meeting due to some miscellaneous problem of its own.</summary>
		MeetingactionresultMiscRemoteError
	}
}
