// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2023 Vidyo, Inc. All rights reserved.


using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;

namespace VidyoClient
{
	public class MeetingFeedback{
		private IntPtr objPtr; //opaque VidyoMeetingFeedback reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
	};
}
